--- 
ClusterName: mycluster
ClusterType: k8s
DockerRun: 
  Config: 
    Cmd: 
      - ./deploy-cluster.sh
    Env: 
      - ANSIBLE_HOST_KEY_CHECKING=False
    Image: "cheyang/k8s-ansible:on-build"
    Tty: true
  HostConfig: 
    Binds: 
      - "/root/ansible.yml:/etc/ansible/group_vars/mycluster.yml"
Driver: aliyun
Properties: 
  aliyunecs-access-key-id: abc
  aliyunecs-access-key-secret: apmaas_api_access
  aliyunecs-image-id: centos7u2_64_40G_cloudinit_20160520.raw
  aliyunecs-instance-type: ecs.s2.small
  aliyunecs-internet-max-bandwidth: 100
  aliyunecs-private-address-only: false
  aliyunecs-region: cn-hongkong
  aliyunecs-security-group: k8s
  aliyunecs-system-disk-category: cloud_efficiency
Vmspecs: 
  - 
    Instances: 1
    Name: kube-master
    Properties: 
      aliyunecs-description: "kube-master,etcd"
      aliyunecs-tag: 
        - kube-master
    Roles: 
      - masters
      - etcd
  - 
    Instances: 2
    Name: kube-slave
    Properties: 
      aliyunecs-description: kube-slave
      aliyunecs-tag: 
        - kube-slave
    roles: 
      - nodes
